<?php

namespace AppBundle\Repository;

/**
 * MountainRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MountainRepository extends \Doctrine\ORM\EntityRepository
{
}
