<?php

namespace AppBundle\Repository;

/**
 * RiverRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RiverRepository extends \Doctrine\ORM\EntityRepository
{
}
